project_name: ssm
release:
  github:
    owner: random1st
    name: ssm-config-editor
  draft: false
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/ssm
    dir: .
    binary: ssmgt
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.buildDate={{.Date}}
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
